name: 'surefire-=report-summary'
description: 'gets summary form surefire report'
inputs:
  file-path:
    required: true
    description: 'file path to the file containing the surefire report'
  fail-on-test-failures:
    required: false
    description: 'if true, the action will fail if there are test failures'
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
