package org.dvsa.testing.framework.stepdefs.TransXchange;

import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.apache.oltu.oauth2.common.exception.OAuthProblemException;
import org.apache.oltu.oauth2.common.exception.OAuthSystemException;
import org.dvsa.testing.framework.Injectors.World;
import org.dvsa.testing.framework.pageObjects.BasePage;
import org.dvsa.testing.framework.stepdefs.vol.Initialisation;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class TransXchange extends BasePage {
    private final World world;
    Initialisation initialisation;
    private int responseCode;

    public TransXchange(World world) {
        this.world = world;
        this.initialisation = new Initialisation(world);
    }

    @Given("I generate an OAuth token")
    public void iGenerateAnOAuthToken() throws OAuthProblemException, OAuthSystemException {
        world.TransXchangeJourney.getAuthToken();
    }

    @When("I upload valid {string} operator xml into the bucket")
    public void iUploadValidOperatorXmlIntoTheBucket(String type) {
        world.TransXchangeJourney.inputValidOperatorXml(type);
    }

    @When("I upload invalid {string} operator xml into the bucket")
    public void iUploadInvalidOperatorXmlIntoTheBucket(String type) {
        world.TransXchangeJourney.inputInvalidOperatorXml(type);
    }

    @Then("I read a message off the queue and verify it looks right for the {string}")
    public void iReadAMessageFromOffTheQueue(String problem) throws IOException {
        world.TransXchangeJourney.getMessagesFromSqs(problem);
    }

    @When("I send a POST request to the API gateway with valid {string} XML")
    public void iSendAPostRequestToTheApiGatewayWithValidTimetableXml(String type) throws Exception {
        this.responseCode = world.TransXchangeJourney.sendValidPdfRequest(type);
    }

    @Then("the response status code should be {int}")
    public void theResponseStatusCodeShouldBe(int statusCode){
        assertEquals(statusCode, responseCode);
    }

    @Then("I get the filename out of the success message in the output queue")
    public void iGetTheFilenameOutOfTheSuccessMessageInTheOutputQueue() {
        world.TransXchangeJourney.getFilenameFromSuccessfulPdfGenerationMessage();
    }

    @And("I verify the file is in the bucket")
    public void iVerifyTheFileIsInTheBucket() {
        world.TransXchangeJourney.verifyFileExistsInOutputBucket();
    }

    @When("I send a POST request to the API gateway with invalid {string} XML")
    public void iSendAPOSTRequestToTheApiGatewayWithTheInvalidXml(String problem) throws Exception {
        this.responseCode = world.TransXchangeJourney.sendInvalidXmlRequest(problem);
    }

    @Given("I do not generate an OAuth token")
    public void iDoNotGenerateAnOAuthToken() {
        //No implementation
    }

    @When("I send an unauthorised POST request to the API gateway with any XML")
    public void iSendAnUnauthorisedPOSTRequestToTheApiGatewayWithAnyXml() throws Exception {
        this.responseCode = world.TransXchangeJourney.sendUnauthorisedRequest();
    }


    @And("I clean up the file generated by this test")
    public void iCleanUpTheFileGeneratedByThisTest() {
        world.TransXchangeJourney.deleteGeneratedFileFromOutputBucket();
    }
}