name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_created: ${{steps.release.outputs.release_created}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: maven
          target-branch: ${{ github.ref_name }}

  build-maven:
    name: Build with Maven
    runs-on: ubuntu-latest
    needs:
      - security
      - get-version
    uses: ./.github/workflows/maven.yaml
    with:
      maven-goal: package -DskipTests

  docker:
    name: Docker
    if: ${{needs.release-please.outputs.release_created}}
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
    with:
      version: ${{ needs.release-please.outputs.tag_name }}
      push: true
      is-release: true
    permissions:
      contents: read
      id-token: write
      packages: write
    needs:
      - build-maven
      - release-please