name: CI

on:
  pull_request:

permissions:
  contents: read
  packages: write


jobs:
  get-version:
    name: Get latest app versions
    runs-on: ubuntu-latest
    outputs:
      vft: ${{ steps.vft-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: vft-version
        uses: ./.github/actions/get-app-version

      - name: Add to summary
        run: |
          echo "#### App versions:" >> $GITHUB_STEP_SUMMARY
          echo "**vft**: \`${{ steps.vft-version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
  security:
    name: Security
    uses: ./.github/workflows/security.yaml
    secrets: inherit

  build-maven:      
    name: build with Maven
    uses: ./.github/workflows/maven.yaml
    with:
        maven-goal: package
    needs: security

  docker:
    name: Docker
    needs: get-version 
    strategy:
      fail-fast: false
    uses: ./.github/workflows/docker.yaml
    with:
      version: ${{ needs.get-version.outputs.vft }}
      push: false
    permissions:
      contents: read
      id-token: write