name: CI

on:
  pull_request:

permissions:
  contents: read
  packages: write


jobs:
  get-version:
    name: Get latest app versions
    runs-on: ubuntu-latest
    outputs:
      vft: ${{ steps.vft-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: vft-version
        uses: ./.github/actions/get-app-version

      - name: Add to summary
        run: |
          echo "#### App versions:" >> $GITHUB_STEP_SUMMARY
          echo "**vft**: \`${{ steps.vft-version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
  security:
    name: Security
    uses: ./.github/workflows/security.yaml
    secrets: inherit

  build-maven:      
    name: build with Maven
    runs-on: ubuntu-latest
    needs: 
      - security
      - get-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get cache key
        id: get-cache-key
        run: echo "cache-key=${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}" >> $GITHUB_OUTPUT

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'


      - uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{ "id":"dvsa-github-packages", "configuration": { "httpHeaders": { "property": { "name":"Authorization", "value":"Bearer ${{ secrets.GITHUB_TOKEN }}"} } } },{ "id":"github-publish", "configuration": { "httpHeaders": { "property": { "name":"Authorization", "value":"Bearer ${{ secrets.GITHUB_TOKEN }}"} } } } ]'

      - name: Build with maven
        run: mvn -B -P github package -DskipTests ${{ inputs.maven-goal}} -Dmaven.repo.local=$HOME/.m2/repository

      - name: Output for cache key
        run: echo "cache-key=${{ steps.get-cache-key.outputs.cache-key }}" >> $GITHUB_OUTPUT
        id: cache-key-output

  docker:
    name: Docker
    needs:
      - build-maven
      - get-version
    strategy:
      fail-fast: false
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.vft }}
      push: ${{ contains(github.event.pull_request.labels.*.name, 'test-branch') || false}}
    permissions:
      contents: read
      id-token: write