name: CI

on:
  pull_request:

permissions:
  contents: read
  packages: write


jobs:
  get-version:
    name: Get latest app versions
    runs-on: ubuntu-latest
    outputs:
      vft: ${{ steps.vft-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: vft-version
        uses: ./.github/actions/get-app-version

      - name: Add to summary
        run: |
          echo "#### App versions:" >> $GITHUB_STEP_SUMMARY
          echo "**vft**: \`${{ steps.vft-version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
  security:
    name: Security
    uses: ./.github/workflows/security.yaml
    secrets: inherit

  build-maven:      
    name: build with Maven
    runs-on : ubuntu-latest
    needs: 
      - security
      - get-version
    steps:
      - uses: actions/checkout@v4

      - name: Get cache key
        id: get-cache-key
        run: echo "cache-key=${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}" >> $GITHUB_OUTPUT

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven build
        uses: ./.github/workflows/maven.yamal
        with:
          maven-goal: package -DskipTests

  docker:
    name: Docker
    needs:
      - build-maven
      - get-version
    strategy:
      fail-fast: false
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
    with:
      maven-cache-key: ${{ steps.get-cache-key.otputs.cache-key }}
      version: ${{ needs.get-version.outputs.vft }}
      push: ${{ contains(github.event.pull_request.labels.*.name, 'test-branch') || false}}
    permissions:
      contents: read
      id-token: write