name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  get-version:
    name: Get latest app versions
    runs-on: ubuntu-latest
    outputs:
      vft: ${{ steps.vft-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - id: vft-version
        uses: ./.github/actions/get-app-version
        with:
          project-path: app/vft
      - name: Add to summary
        run: |
          echo "#### App versions:" >> $GITHUB_STEP_SUMMARY
          echo "**vft**: \`${{ steps.vft-version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY

  docker:
    name: Docker
    needs: get-version 
    strategy:
      fail-fast: false
    uses: ./.github/workflows/docker.yaml
    with:
      version: ${{ needs.get-version.outputs.vft }}
      push: false
    permissions:
      contents: read
      id-token: write