name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  get-version:
    name: Get latest app versions
    runs-on: ubuntu-latest
    outputs:
      vft: ${{ steps.vft-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: vft-version
        uses: dvsa/.github/.github/actions/get-vol-app-version@main

      - name: Add to summary
        run: |
          echo "#### App versions:" >> $GITHUB_STEP_SUMMARY
          echo "**vft**: \`${{ steps.vft-version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY

  security:
    name: Security
    uses: ./.github/workflows/security.yaml
    secrets: inherit

  build-maven:
    name: build with Maven
    uses: ./.github/workflows/maven.yaml
    with:
      maven-goal: package -DskipTests
    needs:
      - security
      - get-version

  docker:
    name: Docker
    needs:
      - build-maven
      - get-version
    strategy:
      fail-fast: false
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      version: ${{ needs.get-version.outputs.vft }}
      push: ${{ github.ref == 'refs/heads/main' || contains(github.ref, 'refs/heads/features/') || contains(github.ref, 'refs/heads/fix/') || contains(github.ref, 'refs/heads/chore/') }}
      image-tag: ${{ github.ref == 'refs/heads/main' && 'latest' || contains(github.ref, 'refs/heads/features/') && format('features-{0}', github.event.pull_request.number) || contains(github.ref, 'refs/heads/fix/') && format('fix-{0}', github.event.pull_request.number) || contains(github.ref, 'refs/heads/chore/') && format('chore-{0}', github.event.pull_request.number) }}