name: CI

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    name: Get latest app versions
    runs-on: ubuntu-latest
    outputs:
      vft: ${{ steps.vft-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: vft-version
        uses: ./.github/actions/get-app-version

      - name: Add to summary
        run: |
          echo "#### App versions:" >> $GITHUB_STEP_SUMMARY
          echo "**vft**: \`${{ steps.vft-version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY

  security:
    name: Security
    uses: ./.github/workflows/security.yaml
    secrets: inherit

  build-maven:
    name: Build with Maven
    runs-on: ubuntu-latest
    needs:
      - security
      - get-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{ "id":"dvsa-github-packages", "configuration": { "httpHeaders": { "property": { "name":"Authorization", "value":"Bearer ${{ secrets.GITHUB_TOKEN }}"} } } }]'

      - name: Build with Maven
        run: mvn -B -P github package -DskipTests

      - name: Cache built JAR
        uses: actions/cache@v3
        with:
          path: target/*.jar
          key: ${{ runner.os }}-artifact-${{ hashFiles('**/pom.xml') }}

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-jar
          path: target/*.jar

  docker:
    name: Docker
    needs: build-maven
    strategy:
      fail-fast: false
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.vft }}
      push: false
    permissions:
      contents: read
      id-token: write