name: Docker

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      push:
        type: boolean
        required: true
        default: false
      is-release:
        type: boolean
        required: false
        default: false
      image-tag:
        type: string
        required: false
        description: 'Custom image tag to push/test (defaults to latest if not provided)'
        default: 'latest'

env:
  WORKING_DIR: infra/docker/batch
  REGISTRY: 054614622558.dkr.ecr.eu-west-1.amazonaws.com
  REGISTRY_MIRROR: ghcr.io
  AWS_OIDC_ROLE: ${{ vars.TEST_OIDC_ROLE }}
  AWS_REGION: ${{ vars.TF_AWS_REGION }}
  BATCH_SETTINGS: '[{ "id": "dvsa-github-packages","username": "${{secrets.SERVICE_USER}}","password": "${{secrets.SERVICE_USER_TOKEN}}"}]'
  RUNNER_SETTINGS: '[{ "id": "dvsa-github-packages","configuration": {"httpHeaders": {"property": {"name": "Authorization","value": "Bearer ${{ secrets.GITHUB_TOKEN }}"}}} }]'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.WORKING_DIR }}/Dockerfile

  build:
    name: Build ${{ inputs.push && 'and push' || '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: whelk-io/maven-settings-xml-action@v22
        name: generate settings xml
        with:
          servers: ${{ inputs.push &&  env.BATCH_SETTINGS || env.RUNNER_SETTINGS }}
          proxies: '[{ "id":"dvsa-ci-proxy", "active": "true", "protocol": "http", "host": "${{vars.CI_PROXY}}", "port": "${{vars.CI_PROXYPORT}}" }]'
          repositories: '[ { "id":"dvsa-github-packages", "name":"dvsa-github-packages", "url":"https://maven.pkg.github.com/dvsa/*", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'
          output_file: ./settings.xml

      - name: view settings.xml
        run: cat ./settings.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta

        uses: docker/metadata-action@v5
        with:
         images: |
           ${{ env.REGISTRY }}/vol-qa/vft
           ${{ env.REGISTRY_MIRROR }}/dvsa/vol-qa/vft
         flavor: |
          latest=auto
         tags: |
          type=raw,value=pr-${{ inputs.image-tag }}
          type=sha,prefix=,format=short

      - name: Configure AWS credentials
        if: ${{ inputs.push && (startsWith(inputs.image-tag, 'feature-') || startsWith(inputs.image-tag, 'fix-') || startsWith(inputs.image-tag, 'chore-')) == false }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE }}
          aws-region: ${{ vars.DVSA_AWS_REGION }}

      - name: Login to ECR
        if: ${{ inputs.push && (startsWith(inputs.image-tag, 'feature-') || startsWith(inputs.image-tag, 'fix-') || startsWith(inputs.image-tag, 'chore-')) == false }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}

      - name: Login to GHCR
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_MIRROR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Untag existing latest image in ECR
        if: ${{ inputs.push && (startsWith(inputs.image-tag, 'feature-') || startsWith(inputs.image-tag, 'fix-') || startsWith(inputs.image-tag, 'chore-')) == false }}
        run: |
          aws ecr batch-delete-image --repository-name vol-qa/vft --image-ids imageTag=latest

      - name: Build ${{ inputs.push && 'and push ' || '' }}Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: infra/docker/batch/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup Notation CLI
        if: ${{ inputs.push && (startsWith(inputs.image-tag, 'feature-') || startsWith(inputs.image-tag, 'fix-') || startsWith(inputs.image-tag, 'chore-')) == false }}
        uses: notaryproject/notation-action/setup@v1
        with:
          version: "1.1.0"

      - name: Sign artefact
        if: ${{ inputs.push && (startsWith(inputs.image-tag, 'feature-') || startsWith(inputs.image-tag, 'fix-') || startsWith(inputs.image-tag, 'chore-')) == false }}
        uses: notaryproject/notation-action/sign@v1
        with:
          plugin_name: com.amazonaws.signer.notation.plugin
          plugin_url: https://d2hvyiie56hcat.cloudfront.net/linux/amd64/plugin/latest/notation-aws-signer-plugin.zip
          plugin_checksum: cccfe8fdcdf853d83fd57ffc80524eddda75ad7ae9d9a257b087007230ec02f9
          key_id: arn:aws:signer:eu-west-1:054614622558:/signing-profiles/vol_qa20240522124422657400000001
          target_artifact_reference: ${{ env.REGISTRY }}/vol-qa/vft@${{ steps.build-and-push.outputs.digest }}