name: E2E Full Regression

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true


jobs:
  call-e2etest:
    name: Call E2E test workflow
    uses: ./.github/workflows/e2etest.yaml
    with:
      platform_env: ${{ inputs.environment }}
      cucumber_tags: "@FullRegression"
      browser_name: "edge"
      browser_version: "latest"
      exclude_tags: "none"

