name: Manual Trigger for End-to-End Test

on:
  workflow_dispatch:
    inputs:
      platform_env:
        type: string
        required: true
        description: "Environment to test"
      browser_name:
        type: string
        required: true
        description: "Browser Name"
      browser_version:
        type: string
        required: true
        description: "Browser Version"
      cucumber_tags:
        type: string
        required: true
        description: "Cucumber Tags"
      maven_options:
        type: string
        required: false
        description: "Maven Options"
      exclude_tags:
          type: string
          required: true
          default: 'none'
          description: "Tages to exclude"
      aws_role:
        description: 'AWS IAM Role ARN to assume'
        required: false
        type: string
      bucket_name:
        description: 'Bucket for test report'
        required: false
        type: string
      bucket_key:
        description: 'Bucket key for report'
        required: false
        type: string
      batch_job_queue:
        description: 'AWS Batch Job Queue'
        required: false
        type: string
      batch_job_definition:
        description: 'AWS Batch Job Definition'
        required: false
        type: string

jobs:
  call-e2etest:
    name: Call E2E Test Workflow
    uses: ./.github/workflows/e2etest.yaml
    with:
      platform_env: ${{ inputs.platform_env }}
      cucumber_tags: ${{ inputs.cucumber_tags }}
      browser_name: ${{ inputs.browser_name }}
      browser_version: ${{ inputs.browser_version }}
      exclude_tags: ${{ inputs.exclude_tags }}
      aws_role: ${{ inputs.aws_role || vars.ACCOUNT_NONPROD_TEST_OIDC_ROLE }}
      bucket_name: ${{ inputs.bucket_name || vars.ACCOUNT_NONPROD_S3_REPORT_BUCKET }}
      bucket_key: ${{ inputs.bucket_key || vars.S3_REPORT_BUCKET_KEY }}
      batch_job_queue: ${{ inputs.batch_job_queue || vars.ACCOUNT_NONPROD_BATCH_JOB_QUEUE }}
      batch_job_definition: ${{ inputs.batch_job_definition || vars.ACCOUNT_NONPROD_BATCH_JOB_DEFINITION }}