name: Manual Trigger for End-to-End Test

on:
  workflow_dispatch:
    inputs:
      test:
        required: true
        type: choice
        options:
          - sync
          - async
      platform_env:
        type: string
        required: true
      browser_name:
        type: string
        required: true
      browser_version:
        type: string
        required: true
      cucumber_tags:
        type: string
        required: true
      maven_options:
        type: string
        required: false


jobs:
  call-e2etest:
    name: Call E2E Test Workflow
    uses: ./.github/workflows/e2etest.yaml
    with:
      platform_env: ${{ inputs.platform_env }}
      cucumber_tags: ${{ inputs.cucumber_tags }}
      browser_name: ${{ inputs.browser_name }}
      browser_version: ${{ inputs.browser_version }}