name: E2E Self Serve Regression

on:
  workflow_call:
    inputs:
      platform_env:
        description: "Environment to deploy"
        type: string
        required: true
      aws_role:
        description: 'AWS IAM Role ARN to assume'
        required: false
        type: string
      bucket_name:
        description: 'Bucket for test report'
        required: true
        type: string
      bucket_key:
        description: 'Bucket key for report'
        required: true
        type: string
      batch_job_queue:
        description: 'AWS Batch Job Queue'
        required: true
        type: string
      batch_job_definition:
        description: 'AWS Batch Job Definition'
        required: true
        type: string
      batch_timeout_minutes:
        type: number
        required: false
        description: "Timeout in minutes for the AWS Batch job"
        default: 60

jobs:
  call-e2etest:
    name: Call E2E test workflow
    uses: ./.github/workflows/e2etest.yaml
    timeout-minutes: ${{ inputs.batch_timeout_minutes }}
    with:
      platform_env: ${{ inputs.platform_env }}
      cucumber_tags: "@ss_regression"
      browser_name: "edge"
      browser_version: "latest"
      exclude_tags: "none"
      aws_role: ${{ inputs.aws_role || vars.ACCOUNT_NONPROD_TEST_OIDC_ROLE }}
      bucket_name: ${{ inputs.bucket_name || vars.ACCOUNT_NONPROD_S3_REPORT_BUCKET }}
      bucket_key: ${{ inputs.bucket_key || vars.S3_REPORT_BUCKET_KEY }}
      batch_job_queue: ${{ inputs.batch_job_queue || vars.ACCOUNT_NONPROD_BATCH_JOB_QUEUE }}
      batch_job_definition: ${{ inputs.batch_job_definition || vars.ACCOUNT_NONPROD_BATCH_JOB_DEFINITION }}