name: E2E Smoke Test
on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy"
        type: string
        required: true

jobs:
  call-e2etest:
    name: Call E2E test workflow
    uses: ./.github/workflows/e2etest.yaml
    with:
      environment: ${{ inputs.environment }}
      cucumber_tags: >-
        ${{
          inputs.environment == 'dev' && '@ec2_smoke' ||
          inputs.environment == 'prep' && '@PP-SMOKE' ||
          '@smoke'
        }}
      browser_name: "edge"
      browser_version: "latest"
      exclude_tags: 'none'