name: End to End Test Manual Trigger

on:
  workflow_dispatch:
    inputs:
      platform_env:
        type: string
        required: true
      browser_name:
        type: string
        required: true
      browser_version:
        type: string
        required: true
      cucumber_tags:
        type: string
        required: true
      exclude_tags:
        type: string
        required: false
      maven_options:
        type: string
        required: false
      aws_settings:
        description: "Comma-separated AWS settings: region,role,bucket,key"
        type: string
        required: true

jobs:
  parse-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Parse AWS Settings
        id: parse-aws-settings
        run: |
          IFS=',' read -r region role bucket key <<< "${{ github.event.inputs.aws_settings }}"
          echo "::set-output name=aws_region::$region"
          echo "::set-output name=aws_oidc_role::$role"
          echo "::set-output name=s3_report_bucket::$bucket"
          echo "::set-output name=s3_report_bucket_key::$key"

      - name: Call Reusable Workflow
        uses: vol-functional-tests/.github/workflows/e2etests.yml@main
        with:
          platform_env: ${{ inputs.platform_env }}
          browser_name: ${{ inputs.browser_name }}
          browser_version: ${{ inputs.browser_version }}
          cucumber_tags: ${{ inputs.cucumber_tags }}
          exclude_tags: ${{ inputs.exclude_tags }}
          maven_options: ${{ inputs.maven_options }}
          aws_region: ${{ steps.parse-aws-settings.outputs.aws_region }}
          aws_oidc_role: ${{ steps.parse-aws-settings.outputs.aws_oidc_role }}
          s3_report_bucket: ${{ steps.parse-aws-settings.outputs.s3_report_bucket }}
          s3_report_bucket_key: ${{ steps.parse-aws-settings.outputs.s3_report_bucket_key }}