name: Functional Test Workflow

on:
  workflow_dispatch:
    inputs:
      platform:
        description: I dont know what this value is
        required: true
        default: 'ubuntu'
      environment:
        description: 'Environment to execute tests'
        required: true
        type: choice
        options:
          - qa
          - int
          - preprod
      branch:
        description: 'Branch to run tests against'
        required: true
        default: main
      browser:
        description: 'Browser to run tests on'
        required: true
      browser_version:
        description: 'Browser version to run tests on'
        required: true
      grid_url:
        description: 'Browser version to run tests on'
        required: true
        default: "https://selenium-hub.olcs.dev-dvsacloud.uk/"
      tags:
        description: 'Test tags to include (comma-separated)'
        required: false
        type: choice
        options:
          - '@smoketest'
          - '@ss_regression'
          - '@int_regression'
          - '@FullRegression'
      excluded_tags:
        description: 'Test tags to exclude (comma-separated)'
        required: false
      clear_maven_cache:
        description: 'Clear Maven cache before running tests'
        required: false
        default: 'false'
      # timeout:
      #   description: 'Timeout in minutes for job execution'
      #   required: false
      compute_mode: 
        description: 'Start or stop the selenium grid cluster platform'
        required: false
        default: 'false'

jobs:
  compute_env: 
    name: Check Compute Environment
    if: ${{ inputs.compute_mode == 'true' }}
    uses: ./.github/workflows/compute-env.yaml
    with:
      account: nonprod
      platform_env: ${{ inputs.environment }}
      mode: ${{ inputs.compute_mode }}
    permissions:
      contents: read
      id-token: write
      pull-requests: write

  maven-test:
    runs-on: ubuntu-latest
    needs: compute_env
    strategy:
      max-parallel: 4
    steps:
      - name: Checkout Project Branch from GitHub
        uses: actions/checkout@v4

      - name: Install Java Corretto 11
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: maven

      - name: Clear Maven cache
        if: ${{ inputs.clear_maven_cache == 'true' }}
        run: mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false

      - name: Deploy Maven Tests to ${{ inputs.environment }}
        env:
          PLATFORM_ENV: ${{ inputs.environment }}
          BROWSER_NAME: ${{ inputs.browser }}
          BROWSER_VERSION: ${{ inputs.browser_version }}
          PLATFORM: ${{ inputs.platform }}
          GRID_URL: ${{ inputs.grid_url }}
          EXCLUDE_TAGS: ${{ inputs.excluded_tags }}
          TAGS: ${{ inputs.tags }}
        run: |
          mvn clean verify -U \
            -Denv=${PLATFORM_ENV} \
            -Dbrowser=${BROWSER_NAME} \
            -DbrowserVersion=${BROWSER_VERSION} \
            -Dplatform=${PLATFORM} \
            -DgridURL="${GRID_URL}" \
            -Dtag.name="(not ${EXCLUDE_TAGS})" \
            -Dcucumber.filter.tags="${TAGS}" \
            -Dwdm.proxy="proxy.web-app.uk:999" \
            -Dhttps.proxyHost="proxy.web-app.uk:999" \
            -Dhttps.proxyPort=3128 \
            -Dhttp.proxyHost="proxy.web-app.uk:999" \
            -Dhttp.proxyPort=3128 \
            -Dhttp.nonProxyHosts="172.17/12|localhost|127.0.0.1|*.web-app.uk"

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Deploy Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
          retention-days: 90